### ISSUE TITLE
`isort` when run via the VSCode extension is inconsistent with the result of running `isort` separately

### ISSUE THREAD

**Issue by HarrisonWilde** [microsoft/vscode-isort#339]
I am currently developing a package. When I use absolute imports within the package to import other parts of the package (e.g. `from mypackage.module import x`), isort on save from VSCode sorts these imports into the 3rd party package "section" at the top of the file. However, when I run `isort` explicitly on the command line on the same project, the absolute imports of parts of my package are separated from the third party ones. This is quite an annoying inconsistency as every time I commit I end up getting a warning from my pre-commit hooks.

The only config I have for isort is this in my `pyproject.toml`:

```toml
[tool.isort]
profile = "black"
```

This is the pre-commit config:

```yaml
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        language_version: python3.11
        args: ["--settings-path", "pyproject.toml"]
```
